### ISSUE TITLE
The ServiceMonitors have wrong port name

### ISSUE THREAD

**Issue by behoof4mind** [GDATASoftwareAG/vaas-helm#85]
Hello,

In current implementation ServiceMonitors will never be discovered by Prometheus Operator.
The problem is that port value should represent the name of the port inside service, which is `http`:
```yaml
kind: Service
metadata:
  name: gateway
....
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
```
The helm chart produces ServiceMonitors which have `"8080"` in port name value instead:
```yaml
kind: ServiceMonitor
metadata:
  name: gateway
spec:
  endpoints:
  - path: /metrics
    port: "8080"
    selector:
      matchLabels:
        app.kubernetes.io/instance: gdata-vaas
        app.kubernetes.io/name: gateway
        app.kubernetes.io/namespace: gdata-vaas

```
The same valid for both gdscan and gateway servicemonitors
https://github.com/GDATASoftwareAG/vaas-helm/blob/7a037a4d2ea4b71eadf7f84299029fe66feaf18c/charts/vaas/templates/gateway/servicemonitor.yaml#L10
https://github.com/GDATASoftwareAG/vaas-helm/blob/7a037a4d2ea4b71eadf7f84299029fe66feaf18c/charts/vaas/templates/gdscan/servicemonitor.yaml#L10
---
```shell
kubectl explain servicemonitor.spec.endpoints:

   port <string>
     Name of the Service port which this endpoint refers to.

     It takes precedence over `targetPort`.
.........
   targetPort   <>
     Name or number of the target port of the `Pod` object behind the Service.
     The port must be specified with the container's port property.
```
