### ISSUE TITLE
NetworkPolicies are not allow to scrape Prometheus metrics

### ISSUE THREAD

**Issue by behoof4mind** [GDATASoftwareAG/vaas-helm#87]
Hello,

To get metrics we need to have extra selector in the policies. Example:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gdscan
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: gdata-vaas
          app.kubernetes.io/name: gateway
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: prometheus
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
....
```
So it should be possible somehow to specify Prometheus related labelSelectors in case if metrics value is equal to true.
This is related for both gateway and gdscan metrics scrapes.

**Comment by pstadermann** [comment]
This is implemented in the next release 2.5.0.

To get your desired NetworkPolicies, set this in your values.yaml:

```yaml
gateway:
  networkPolicy:
    enabled: true
    ingressNSMatchLabels:
      kubernetes.io/metadata.name: prometheus
    ingressNSPodMatchLabels:
      app.kubernetes.io/name: prometheus

gdscan:
  networkPolicy:
    enabled: true
    ingressNSMatchLabels:
      kubernetes.io/metadata.name: prometheus
    ingressNSPodMatchLabels:
      app.kubernetes.io/name: prometheus
```
